INSERT INTO care_tips (
  slug,
  title,
  summary,
  content,
  category,
  suitable_plants,
  related_disease_id,
  priority,
  is_active,
  start_date,
  end_date,
  source_name,
  source_url,
  source_note
)
VALUES
(
  'tuoi-nuoc-vao-buoi-sang',
  'Tưới nước vào buổi sáng',
  'Tưới sớm giúp lá khô nhanh và giảm nguy cơ bệnh lá.',
  'Nên tưới cây vào buổi sáng để cây hấp thụ nước tốt hơn trong ngày. Lá khô nhanh trước chiều tối sẽ giảm điều kiện thuận lợi cho nấm bệnh. Đây là thói quen quan trọng với hầu hết cây trồng trong vườn nhà.',
  'Tưới nước',
  '["Cà chua", "Ớt", "Rau cải", "Dưa leo"]'::jsonb,
  NULL,
  100,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/disease-management/bacterial-spot-tomato-and-pepper',
  'Nguồn khuyến nghị giữ lá khô, tưới ở gốc và theo dõi sớm dấu hiệu bệnh lá.'
),
(
  'tuoi-vao-goc-thay-vi-tuoi-len-la',
  'Tưới vào gốc thay vì tưới trực tiếp lên lá',
  'Tập trung tưới vùng rễ giúp cây nhận nước và hạn chế lá ướt lâu.',
  'Khi tưới vào gốc, rễ nhận nước hiệu quả hơn và bề mặt lá ít bị ẩm kéo dài. Điều này giúp giảm nguy cơ đốm lá do vi khuẩn và nấm. Với cây chậu, hãy tưới chậm để nước ngấm đều quanh bầu đất.',
  'Tưới nước',
  '["Cà chua", "Ớt", "Dâu tây", "Rau thơm"]'::jsonb,
  NULL,
  99,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'khong-de-la-am-qua-dem',
  'Không để lá ẩm qua đêm',
  'Lá ướt kéo dài ban đêm làm tăng nguy cơ nấm bệnh.',
  'Tránh tưới muộn vào chiều tối vì lá sẽ khó khô khi nhiệt độ giảm. Lá ẩm qua đêm là điều kiện thuận lợi cho nhiều bệnh lá phát triển nhanh. Nếu thời tiết ẩm kéo dài, cần tăng tần suất quan sát cây.',
  'Tưới nước',
  '["Cà chua", "Dưa leo", "Bầu bí", "Rau lá"]'::jsonb,
  NULL,
  98,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/plant-diseases/tomato-leaf-spot-diseases',
  'Nguồn lưu ý theo dõi đốm lá, giảm ẩm trên lá và xử lý sớm vùng bị bệnh.'
),
(
  'uu-tien-tuoi-nho-giot-hoac-voi-tham',
  'Dùng tưới nhỏ giọt hoặc vòi thấm nếu có thể',
  'Tưới nhỏ giọt giúp ổn định ẩm đất và giảm bắn nước lên lá.',
  'Hệ thống nhỏ giọt cấp nước từ từ ngay vùng rễ nên tiết kiệm nước và hiệu quả hơn. Việc giảm nước bắn lên lá cũng giúp hạn chế lây mầm bệnh từ đất. Đây là lựa chọn tốt cho vườn trồng nhiều luống.',
  'Tưới nước',
  '["Ớt", "Cà chua", "Dưa leo", "Rau ăn lá"]'::jsonb,
  NULL,
  97,
  TRUE,
  NULL,
  NULL,
  'UF/IFAS Extension',
  'https://gardeningsolutions.ifas.ufl.edu/care/pests-and-diseases/pests/integrated-pest-management/',
  'Nguồn IPM khuyến nghị phòng ngừa chủ động, vệ sinh khu trồng và giảm áp lực sâu bệnh.'
),
(
  'kiem-tra-do-am-dat-truoc-khi-tuoi',
  'Kiểm tra độ ẩm đất trước khi tưới',
  'Kiểm tra đất trước giúp tránh tưới thừa hoặc thiếu nước.',
  'Dùng tay kiểm tra lớp đất mặt hoặc vùng rễ nông trước khi tưới. Nếu đất còn ẩm, nên lùi thời điểm tưới để tránh úng rễ. Thói quen này giúp cây ổn định hơn theo biến động thời tiết.',
  'Tưới nước',
  '["Rau cải", "Cà chua", "Ớt", "Hoa cảnh"]'::jsonb,
  NULL,
  96,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'khong-tuoi-qua-nhieu-gay-ung-re',
  'Không tưới quá nhiều gây úng rễ',
  'Tưới quá mức có thể làm rễ thiếu oxy và cây suy yếu.',
  'Đất quá ướt lâu ngày khiến rễ giảm khả năng hấp thụ dinh dưỡng. Cây dễ vàng lá, chậm phát triển và nhạy cảm hơn với bệnh. Hãy điều chỉnh lượng tưới theo mùa và khả năng thoát nước của giá thể.',
  'Tưới nước',
  '["Cà chua", "Ớt", "Rau ăn lá", "Đậu"]'::jsonb,
  NULL,
  95,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/disease-management/late-blight',
  'Nguồn khuyến nghị tăng giám sát khi thời tiết ẩm mát và giảm nguy cơ lây bệnh trong vườn.'
),
(
  'cat-bo-la-bi-benh-som',
  'Cắt bỏ lá bị bệnh sớm',
  'Loại bỏ lá bệnh sớm giúp giảm lây lan trong vườn.',
  'Khi thấy lá có đốm bệnh rõ rệt, nên cắt bỏ sớm để giảm nguồn lây. Dụng cụ cắt cần sạch để tránh mang mầm bệnh sang cây khác. Nếu bệnh lan nhanh, nên theo dõi thêm và tham khảo chuyên gia nông nghiệp.',
  'Phòng bệnh',
  '["Cà chua", "Khoai tây", "Ớt", "Cà tím"]'::jsonb,
  NULL,
  94,
  TRUE,
  NULL,
  NULL,
  'Penn State Extension',
  'https://extension.psu.edu/tomato-potato-late-blight-in-the-home-garden/',
  'Nguồn nhấn mạnh phát hiện sớm, loại bỏ mô bệnh và theo dõi sát cây có nguy cơ cao.'
),
(
  'thu-gom-la-benh-roi-duoi-goc',
  'Thu gom lá bệnh rơi dưới gốc',
  'Lá bệnh rơi dưới gốc là nguồn bệnh tồn lưu cần dọn sớm.',
  'Tàn dư lá bệnh có thể tiếp tục chứa mầm bệnh và tái nhiễm cho cây. Thu gom định kỳ giúp giảm áp lực bệnh theo thời gian. Giữ mặt luống sạch cũng giúp bạn quan sát triệu chứng mới dễ hơn.',
  'Phòng bệnh',
  '["Dâu tây", "Cà chua", "Rau cải", "Cây ăn quả"]'::jsonb,
  NULL,
  93,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'cach-ly-cay-co-dau-hieu-benh-nang',
  'Cách ly cây có dấu hiệu bệnh nặng',
  'Tách cây bệnh nặng giúp giảm nguy cơ lây sang cây khỏe.',
  'Khi một cây có triệu chứng nặng, nên đặt cây đó xa khu vực trồng chính. Việc cách ly giúp bạn kiểm soát tốt hơn và hạn chế lây nhiễm chéo. Nếu tình trạng xấu đi nhanh, cần tham khảo tư vấn kỹ thuật sớm.',
  'Phòng bệnh',
  '["Hoa cảnh", "Rau lá", "Cà chua", "Ớt"]'::jsonb,
  NULL,
  92,
  TRUE,
  NULL,
  NULL,
  'Penn State Extension',
  'https://extension.psu.edu/tomato-potato-late-blight-in-the-home-garden/',
  'Nguồn nhấn mạnh phát hiện sớm, loại bỏ mô bệnh và theo dõi sát cây có nguy cơ cao.'
),
(
  'khong-dung-hat-giong-tu-cay-bi-benh',
  'Không dùng hạt giống từ cây bị bệnh',
  'Chọn nguồn giống sạch giúp giảm rủi ro bệnh từ đầu vụ.',
  'Hạt từ cây có triệu chứng bệnh có thể mang rủi ro cho lứa trồng mới. Nên ưu tiên nguồn giống tin cậy, rõ xuất xứ và khỏe mạnh. Đây là bước phòng bệnh quan trọng ngay từ đầu chu kỳ trồng.',
  'Phòng bệnh',
  '["Cà chua", "Ớt", "Dưa leo", "Rau cải"]'::jsonb,
  NULL,
  91,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/disease-management/bacterial-spot-tomato-and-pepper',
  'Nguồn khuyến nghị giữ lá khô, tưới ở gốc và theo dõi sớm dấu hiệu bệnh lá.'
),
(
  'theo-doi-cay-khi-thoi-tiet-am-keo-dai',
  'Theo dõi cây khi thời tiết ẩm kéo dài',
  'Giai đoạn ẩm kéo dài là lúc bệnh lá dễ bùng phát.',
  'Khi trời mưa dầm hoặc độ ẩm cao nhiều ngày, nên kiểm tra cây thường xuyên hơn. Đốm lá và mốc thường tiến triển nhanh trong điều kiện này. Ghi nhận triệu chứng theo ngày để phát hiện xu hướng xấu sớm.',
  'Phòng bệnh',
  '["Cà chua", "Dưa leo", "Ớt", "Rau lá"]'::jsonb,
  NULL,
  90,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/disease-management/late-blight',
  'Nguồn khuyến nghị tăng giám sát khi thời tiết ẩm mát và giảm nguy cơ lây bệnh trong vườn.'
),
(
  'phat-hien-som-dom-la-moi-xuat-hien',
  'Phát hiện sớm đốm lá mới xuất hiện',
  'Theo dõi đốm lá mới giúp xử lý kịp thời trước khi lan rộng.',
  'Ngay khi thấy đốm nhỏ bất thường, nên chụp ảnh và quan sát lại sau 24 đến 48 giờ. So sánh tiến triển giúp bạn đánh giá mức độ nghiêm trọng chính xác hơn. Nếu đốm lan nhanh, cần tăng mức theo dõi hoặc xin tư vấn chuyên môn.',
  'Phòng bệnh',
  '["Cà chua", "Ớt", "Cây ăn quả", "Rau cải"]'::jsonb,
  NULL,
  89,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/plant-diseases/tomato-leaf-spot-diseases',
  'Nguồn lưu ý theo dõi đốm lá, giảm ẩm trên lá và xử lý sớm vùng bị bệnh.'
),
(
  'kiem-tra-mat-duoi-la-thuong-xuyen',
  'Kiểm tra mặt dưới lá thường xuyên',
  'Mặt dưới lá thường xuất hiện sớm dấu hiệu sâu bệnh.',
  'Nhiều loài rệp và trứng sâu tập trung ở mặt dưới lá hoặc chồi non. Kiểm tra định kỳ giúp phát hiện sớm trước khi chúng lan rộng. Thao tác này chỉ mất ít phút nhưng rất hiệu quả cho quản lý vườn.',
  'Theo dõi cây',
  '["Ớt", "Cà tím", "Dưa leo", "Rau cải"]'::jsonb,
  NULL,
  88,
  TRUE,
  NULL,
  NULL,
  'Clemson Cooperative Extension',
  'https://hgic.clemson.edu/factsheet/integrated-pest-management-i-p-m-for-aphids/',
  'Nguồn IPM khuyến nghị kiểm tra mặt dưới lá và chồi non để phát hiện rệp sớm.'
),
(
  'quan-sat-mau-la-moi-tuan',
  'Quan sát màu lá mỗi tuần',
  'Màu lá thay đổi là tín hiệu sớm về sức khỏe cây.',
  'Hãy dành một mốc cố định mỗi tuần để quan sát màu lá toàn cây. Lá nhợt, vàng hoặc loang màu có thể liên quan đến dinh dưỡng hoặc bệnh. Theo dõi đều đặn giúp bạn điều chỉnh chăm sóc đúng lúc.',
  'Theo dõi cây',
  '["Rau lá", "Ớt", "Cà chua", "Hoa cảnh"]'::jsonb,
  NULL,
  87,
  TRUE,
  NULL,
  NULL,
  'University of California Agriculture and Natural Resources',
  'https://ipm.ucanr.edu/',
  'Nguồn IPM khuyến nghị giám sát thường xuyên, xử lý sớm và ưu tiên biện pháp canh tác an toàn.'
),
(
  'ghi-lai-lich-su-quet-de-theo-doi-tai-phat',
  'Ghi lại lịch sử quét để theo dõi bệnh tái phát',
  'Lịch sử quét giúp nhận ra bệnh tái phát theo thời gian.',
  'Mỗi lần quét nên lưu ảnh, thời gian và kết quả để đối chiếu về sau. Dữ liệu liên tục sẽ giúp nhận ra bệnh lặp lại theo mùa hoặc theo điều kiện chăm sóc. Khi thấy xu hướng tái phát, bạn có thể chủ động điều chỉnh sớm.',
  'Theo dõi cây',
  '["Cà chua", "Ớt", "Rau cải", "Cây ăn quả"]'::jsonb,
  NULL,
  86,
  TRUE,
  NULL,
  NULL,
  'UF/IFAS Extension',
  'https://gardeningsolutions.ifas.ufl.edu/care/pests-and-diseases/pests/integrated-pest-management/',
  'Nguồn IPM khuyến nghị phòng ngừa chủ động, vệ sinh khu trồng và giảm áp lực sâu bệnh.'
),
(
  'kiem-tra-cay-moi-mua-truoc-khi-trong',
  'Kiểm tra cây mới mua trước khi trồng',
  'Quan sát cây mới giúp tránh đưa mầm bệnh vào vườn.',
  'Trước khi trồng cây mới, nên kiểm tra lá, thân và vùng gốc thật kỹ. Nếu có thể, theo dõi riêng vài ngày trước khi đặt vào khu trồng chính. Đây là biện pháp phòng ngừa hiệu quả và dễ thực hiện.',
  'Theo dõi cây',
  '["Hoa cảnh", "Rau thơm", "Cây ăn quả", "Rau lá"]'::jsonb,
  NULL,
  85,
  TRUE,
  NULL,
  NULL,
  'UF/IFAS Extension',
  'https://gardeningsolutions.ifas.ufl.edu/care/pests-and-diseases/pests/integrated-pest-management/',
  'Nguồn IPM khuyến nghị phòng ngừa chủ động, vệ sinh khu trồng và giảm áp lực sâu bệnh.'
),
(
  'kiem-tra-sau-benh-sau-mua',
  'Kiểm tra sâu bệnh sau mưa',
  'Sau mưa, cây cần được kiểm tra lại để phát hiện rủi ro sớm.',
  'Độ ẩm cao sau mưa có thể làm sâu bệnh tăng nhanh hơn bình thường. Hãy kiểm tra lá non, mặt dưới lá và vùng gốc sau mỗi đợt mưa lớn. Việc theo dõi sớm giúp tránh xử lý muộn khi bệnh đã lan.',
  'Theo dõi cây',
  '["Cà chua", "Dưa leo", "Đậu", "Rau cải"]'::jsonb,
  NULL,
  84,
  TRUE,
  NULL,
  NULL,
  'Penn State Extension',
  'https://extension.psu.edu/tomato-potato-late-blight-in-the-home-garden/',
  'Nguồn nhấn mạnh phát hiện sớm, loại bỏ mô bệnh và theo dõi sát cây có nguy cơ cao.'
),
(
  'theo-doi-la-non-de-phat-hien-rep-som',
  'Theo dõi lá non vì thường dễ bị rệp tấn công',
  'Lá non là vị trí rệp thường xuất hiện sớm và tăng nhanh.',
  'Rệp thường tập trung ở chồi non vì mô mềm và giàu dinh dưỡng. Quan sát kỹ lá non giúp bạn phát hiện dấu hiệu sớm hơn các vùng khác. Khi mật độ rệp còn thấp, việc kiểm soát sẽ dễ hơn đáng kể.',
  'Theo dõi cây',
  '["Ớt", "Cà chua", "Rau cải", "Hoa cảnh"]'::jsonb,
  NULL,
  83,
  TRUE,
  NULL,
  NULL,
  'Clemson Cooperative Extension',
  'https://hgic.clemson.edu/factsheet/integrated-pest-management-i-p-m-for-aphids/',
  'Nguồn IPM khuyến nghị kiểm tra mặt dưới lá và chồi non để phát hiện rệp sớm.'
),
(
  'khong-bon-phan-qua-lieu',
  'Không bón phân quá liều',
  'Bón quá mức có thể làm cây stress và tăng nhạy cảm với bệnh.',
  'Nên bón phân theo nhu cầu thực tế thay vì tăng liều đột ngột. Dư phân có thể gây mất cân bằng sinh trưởng và làm cây yếu hơn. Theo dõi phản ứng của lá và rễ sau mỗi lần bón để điều chỉnh phù hợp.',
  'Dinh dưỡng',
  '["Rau ăn lá", "Cà chua", "Ớt", "Dưa leo"]'::jsonb,
  NULL,
  82,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'tranh-bon-qua-nhieu-dam',
  'Tránh bón quá nhiều đạm',
  'Đạm cao dễ làm tán lá non mềm và tăng nguy cơ sâu bệnh.',
  'Bón đạm quá nhiều có thể làm cây tốt lá nhanh nhưng mô lá yếu. Lá mềm thường dễ bị côn trùng tấn công và nhiễm bệnh hơn. Ưu tiên chế độ dinh dưỡng cân đối theo giai đoạn phát triển.',
  'Dinh dưỡng',
  '["Cà chua", "Ớt", "Rau cải", "Rau thơm"]'::jsonb,
  NULL,
  81,
  TRUE,
  NULL,
  NULL,
  'UF/IFAS Extension',
  'https://gardeningsolutions.ifas.ufl.edu/care/pests-and-diseases/pests/integrated-pest-management/',
  'Nguồn IPM khuyến nghị phòng ngừa chủ động, vệ sinh khu trồng và giảm áp lực sâu bệnh.'
),
(
  'bo-sung-dinh-duong-can-doi',
  'Bổ sung dinh dưỡng cân đối',
  'Dinh dưỡng cân đối giúp cây khỏe và chống chịu tốt hơn.',
  'Không nên chỉ tập trung vào một loại dinh dưỡng duy nhất. Cây cần chế độ cân đối để duy trì tăng trưởng ổn định và giảm stress. Khi cây khỏe, khả năng chống chịu bệnh cũng thường tốt hơn.',
  'Dinh dưỡng',
  '["Rau lá", "Ớt", "Cà chua", "Cây ăn quả"]'::jsonb,
  NULL,
  80,
  TRUE,
  NULL,
  NULL,
  'University of California Agriculture and Natural Resources',
  'https://ipm.ucanr.edu/',
  'Nguồn IPM khuyến nghị giám sát thường xuyên, xử lý sớm và ưu tiên biện pháp canh tác an toàn.'
),
(
  'quan-sat-la-vang-de-phat-hien-thieu-dinh-duong',
  'Quan sát lá vàng để phát hiện thiếu dinh dưỡng',
  'Lá vàng bất thường có thể là tín hiệu thiếu dinh dưỡng hoặc rễ kém.',
  'Khi thấy lá vàng, hãy quan sát vị trí xuất hiện ở lá già hay lá non. Dấu hiệu này có thể liên quan dinh dưỡng, tưới nước hoặc tình trạng rễ. Theo dõi theo thời gian giúp bạn phân biệt rõ nguyên nhân hơn.',
  'Dinh dưỡng',
  '["Rau cải", "Cà chua", "Ớt", "Đậu"]'::jsonb,
  NULL,
  79,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'bon-phan-theo-giai-doan-sinh-truong',
  'Bón phân theo giai đoạn sinh trưởng',
  'Mỗi giai đoạn cây cần chế độ dinh dưỡng khác nhau.',
  'Cây con, giai đoạn sinh trưởng và giai đoạn ra hoa kết trái có nhu cầu khác nhau. Bón đúng thời điểm giúp cây sử dụng hiệu quả và giảm dư thừa dinh dưỡng. Cách này hỗ trợ cây phát triển ổn định và bền hơn.',
  'Dinh dưỡng',
  '["Cà chua", "Ớt", "Dưa leo", "Cây ăn quả"]'::jsonb,
  NULL,
  78,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'khong-bon-phan-khi-cay-qua-yeu-chua-ro-nguyen-nhan',
  'Không bón phân khi cây đang quá yếu nếu chưa xác định nguyên nhân',
  'Cây suy yếu chưa rõ nguyên nhân cần được quan sát trước khi bón thêm.',
  'Khi cây đang héo hoặc suy rõ, bón phân ngay có thể làm tình trạng nặng hơn. Nên kiểm tra nước tưới, rễ và triệu chứng bệnh trước khi điều chỉnh dinh dưỡng. Cách tiếp cận thận trọng giúp tránh xử lý sai hướng.',
  'Dinh dưỡng',
  '["Rau lá", "Cà chua", "Ớt", "Hoa cảnh"]'::jsonb,
  NULL,
  77,
  TRUE,
  NULL,
  NULL,
  'University of California Agriculture and Natural Resources',
  'https://ipm.ucanr.edu/',
  'Nguồn IPM khuyến nghị giám sát thường xuyên, xử lý sớm và ưu tiên biện pháp canh tác an toàn.'
),
(
  'dat-cay-o-noi-thong-thoang',
  'Đặt cây ở nơi thông thoáng',
  'Thông thoáng giúp lá khô nhanh và giảm tích tụ độ ẩm.',
  'Không khí lưu thông tốt giúp giảm môi trường thuận lợi cho nấm bệnh. Khu vực quá bí thường giữ ẩm lâu và làm bệnh lan nhanh hơn. Ưu tiên vị trí có gió nhẹ và ánh sáng phù hợp.',
  'Môi trường trồng',
  '["Rau lá", "Cây gia vị", "Hoa", "Cà chua"]'::jsonb,
  NULL,
  76,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'trong-cay-voi-mat-do-hop-ly',
  'Trồng cây với mật độ hợp lý',
  'Mật độ hợp lý giảm che phủ tán và hỗ trợ thông khí.',
  'Khi trồng quá dày, ánh sáng và không khí khó xuyên qua tán lá. Điều này làm tăng độ ẩm cục bộ và nguy cơ bệnh lá. Giữ mật độ phù hợp giúp cây phát triển cân đối hơn.',
  'Môi trường trồng',
  '["Rau cải", "Cà chua", "Ớt", "Ngũ cốc"]'::jsonb,
  NULL,
  75,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'dam-bao-cay-nhan-du-anh-sang-phu-hop',
  'Đảm bảo cây nhận đủ ánh sáng phù hợp',
  'Ánh sáng phù hợp giúp cây khỏe và giảm suy yếu do thiếu quang hợp.',
  'Mỗi loại cây có nhu cầu ánh sáng khác nhau nên cần đặt đúng vị trí. Cây thiếu sáng kéo dài thường yếu và dễ gặp vấn đề bệnh lá. Theo dõi phản ứng của cây để điều chỉnh vị trí kịp thời.',
  'Ánh sáng',
  '["Rau thơm", "Rau lá", "Cà chua", "Hoa cảnh"]'::jsonb,
  NULL,
  74,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'tranh-dat-cay-o-noi-qua-bi-gio',
  'Tránh đặt cây ở nơi quá bí gió',
  'Khu vực bí gió giữ ẩm lâu và dễ phát sinh bệnh hơn.',
  'Không nên đặt chậu sát tường kín hoặc các góc ít lưu thông không khí. Môi trường bí làm lá lâu khô sau tưới hoặc mưa. Điều chỉnh vị trí trồng sẽ giúp giảm áp lực bệnh lâu dài.',
  'Môi trường trồng',
  '["Hoa cảnh", "Rau chậu", "Ớt", "Dưa leo"]'::jsonb,
  NULL,
  73,
  TRUE,
  NULL,
  NULL,
  'UF/IFAS Extension',
  'https://gardeningsolutions.ifas.ufl.edu/care/pests-and-diseases/pests/integrated-pest-management/',
  'Nguồn IPM khuyến nghị phòng ngừa chủ động, vệ sinh khu trồng và giảm áp lực sâu bệnh.'
),
(
  'che-chan-khi-nang-gat-keo-dai',
  'Che chắn khi nắng gắt kéo dài',
  'Giảm sốc nhiệt giúp cây phục hồi tốt và ít suy yếu hơn.',
  'Nắng gắt liên tục có thể làm cây mất nước nhanh và giảm sức đề kháng. Dùng lưới che phù hợp vào khung giờ nắng đỉnh điểm giúp cây ổn định hơn. Sau đó vẫn cần đảm bảo cây nhận đủ ánh sáng tổng thể.',
  'Chăm sóc theo mùa',
  '["Rau lá", "Ớt", "Hoa cảnh", "Dưa leo"]'::jsonb,
  NULL,
  72,
  TRUE,
  NULL,
  NULL,
  'University of California Agriculture and Natural Resources',
  'https://ipm.ucanr.edu/',
  'Nguồn IPM khuyến nghị giám sát thường xuyên, xử lý sớm và ưu tiên biện pháp canh tác an toàn.'
),
(
  'giu-khoang-cach-giua-cac-chau-cay',
  'Giữ khoảng cách giữa các chậu cây',
  'Khoảng cách chậu hợp lý giúp giảm lây bệnh chéo.',
  'Đặt chậu quá sát nhau khiến tán lá chạm trực tiếp và tăng lây lan bệnh. Giữ khoảng hở phù hợp giúp thông khí tốt hơn và dễ kiểm tra từng cây. Đây là thay đổi nhỏ nhưng tác động rõ rệt đến sức khỏe vườn.',
  'Môi trường trồng',
  '["Hoa cảnh", "Rau chậu", "Ớt", "Cà chua"]'::jsonb,
  NULL,
  71,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'tia-la-gia-dinh-ky',
  'Tỉa lá già định kỳ',
  'Tỉa lá già giúp cây thông thoáng và tập trung dinh dưỡng tốt hơn.',
  'Lá già gần gốc thường dễ giữ ẩm và tích tụ mầm bệnh. Tỉa định kỳ giúp tán lá gọn và giảm rủi ro lây nhiễm từ lá thấp. Thực hiện nhẹ nhàng để tránh làm tổn thương thân chính.',
  'Cắt tỉa',
  '["Cà chua", "Ớt", "Cà tím", "Dưa leo"]'::jsonb,
  NULL,
  70,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/plant-diseases/tomato-leaf-spot-diseases',
  'Nguồn lưu ý theo dõi đốm lá, giảm ẩm trên lá và xử lý sớm vùng bị bệnh.'
),
(
  'khong-cat-qua-nhieu-la-cung-luc',
  'Không cắt quá nhiều lá cùng lúc',
  'Tỉa quá tay có thể làm cây sốc và giảm sức phục hồi.',
  'Nên tỉa từng phần nhỏ theo nhiều đợt để cây thích nghi tốt hơn. Mất quá nhiều lá trong một lần sẽ ảnh hưởng quang hợp và tăng stress. Ưu tiên loại bỏ lá bệnh và lá già trước.',
  'Cắt tỉa',
  '["Cà chua", "Ớt", "Hoa cảnh", "Cây ăn quả non"]'::jsonb,
  NULL,
  69,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/plant-diseases/leaf-spot-diseases-trees-and-shrubs',
  'Nguồn khuyến nghị cắt tỉa hợp lý, vệ sinh tàn dư và giảm điều kiện lây lan bệnh lá.'
),
(
  've-sinh-dung-cu-cat-tia',
  'Vệ sinh dụng cụ cắt tỉa',
  'Dụng cụ sạch giúp giảm lây bệnh qua vết cắt.',
  'Kéo, dao và dụng cụ cắt nên được làm sạch thường xuyên trong lúc làm vườn. Điều này giúp hạn chế truyền mầm bệnh từ cây bệnh sang cây khỏe. Đặc biệt cần chú ý sau khi cắt mô đã nhiễm bệnh.',
  'Cắt tỉa',
  '["Cây ăn quả", "Hoa cảnh", "Cà chua", "Ớt"]'::jsonb,
  NULL,
  68,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/plant-diseases/leaf-spot-diseases-trees-and-shrubs',
  'Nguồn khuyến nghị cắt tỉa hợp lý, vệ sinh tàn dư và giảm điều kiện lây lan bệnh lá.'
),
(
  'cat-bo-canh-la-cham-dat',
  'Cắt bỏ cành hoặc lá chạm đất',
  'Lá chạm đất dễ nhiễm mầm bệnh từ đất và tàn dư.',
  'Các lá hoặc cành chạm đất thường giữ ẩm và dính bùn sau mưa. Cắt bỏ phần này giúp giảm nguy cơ bệnh lan từ đất lên cây. Sau khi cắt nên theo dõi lại vết cắt và độ thông thoáng tán.',
  'Cắt tỉa',
  '["Cà chua", "Ớt", "Dưa leo", "Đậu"]'::jsonb,
  NULL,
  67,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/plant-diseases/tomato-leaf-spot-diseases',
  'Nguồn lưu ý theo dõi đốm lá, giảm ẩm trên lá và xử lý sớm vùng bị bệnh.'
),
(
  'tia-bot-tan-la-qua-day',
  'Tỉa bớt tán lá quá dày',
  'Tán lá dày cần được tỉa bớt để tăng ánh sáng và thông khí.',
  'Tán lá rậm làm ánh sáng khó xuyên qua và độ ẩm tăng cao ở bên trong. Tỉa bớt hợp lý giúp lá khô nhanh hơn sau tưới hoặc mưa. Đây là biện pháp giảm bệnh lá hiệu quả trong mùa ẩm.',
  'Cắt tỉa',
  '["Cà chua", "Nho", "Hoa hồng", "Cây ăn quả"]'::jsonb,
  NULL,
  66,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'cat-bo-phan-cay-da-thoi-hong',
  'Cắt bỏ phần cây đã thối hoặc hỏng',
  'Mô thối hỏng cần loại bỏ để giảm nguồn bệnh tồn tại.',
  'Phần cây thối thường là nơi mầm bệnh phát triển mạnh và lây lan sang mô khỏe. Loại bỏ sớm giúp cây tập trung phục hồi ở vùng còn tốt. Nếu hiện tượng thối lan nhanh, nên theo dõi sát và xin tư vấn chuyên môn.',
  'Cắt tỉa',
  '["Cà chua", "Ớt", "Hoa cảnh", "Dâu tây"]'::jsonb,
  NULL,
  65,
  TRUE,
  NULL,
  NULL,
  'Penn State Extension',
  'https://extension.psu.edu/tomato-potato-late-blight-in-the-home-garden/',
  'Nguồn nhấn mạnh phát hiện sớm, loại bỏ mô bệnh và theo dõi sát cây có nguy cơ cao.'
),
(
  'theo-doi-rep-o-choi-non-va-mat-duoi-la',
  'Theo dõi rệp ở chồi non và mặt dưới lá',
  'Rệp phát triển nhanh ở chồi non nên cần kiểm tra thường xuyên.',
  'Rệp hút nhựa có thể làm lá quăn và cây chậm lớn nếu không phát hiện sớm. Hãy tập trung kiểm tra chồi non và mặt dưới lá 2 đến 3 lần mỗi tuần. Phát hiện sớm sẽ giúp xử lý nhẹ nhàng hơn.',
  'Kiểm soát sâu hại',
  '["Ớt", "Cà chua", "Rau cải", "Hoa cảnh"]'::jsonb,
  NULL,
  64,
  TRUE,
  NULL,
  NULL,
  'Clemson Cooperative Extension',
  'https://hgic.clemson.edu/factsheet/integrated-pest-management-i-p-m-for-aphids/',
  'Nguồn IPM khuyến nghị kiểm tra mặt dưới lá và chồi non để phát hiện rệp sớm.'
),
(
  'kiem-tra-dau-hieu-sau-an-la',
  'Kiểm tra dấu hiệu sâu ăn lá',
  'Vết thủng hoặc mép lá bị cắn là tín hiệu sâu ăn lá cần lưu ý.',
  'Quan sát định kỳ để phát hiện sớm các lỗ cắn mới trên lá. Khi mức độ còn nhẹ, bạn có thể xử lý nhanh trước khi sâu tăng mật độ. Kết hợp theo dõi vào sáng sớm hoặc chiều mát để dễ nhận biết.',
  'Kiểm soát sâu hại',
  '["Rau cải", "Cải xanh", "Dưa leo", "Đậu"]'::jsonb,
  NULL,
  63,
  TRUE,
  NULL,
  NULL,
  'University of California Agriculture and Natural Resources',
  'https://ipm.ucanr.edu/',
  'Nguồn IPM khuyến nghị giám sát thường xuyên, xử lý sớm và ưu tiên biện pháp canh tác an toàn.'
),
(
  'loai-bo-sau-hai-thu-cong-khi-so-luong-it',
  'Loại bỏ sâu hại thủ công khi số lượng ít',
  'Xử lý thủ công sớm giúp giảm áp lực sâu hại ban đầu.',
  'Khi mới xuất hiện vài cá thể sâu, có thể loại bỏ thủ công để hạn chế lan rộng. Cách này phù hợp với vườn nhỏ và giúp giảm can thiệp không cần thiết. Sau khi loại bỏ, nên tiếp tục theo dõi thêm vài ngày.',
  'Kiểm soát sâu hại',
  '["Rau ăn lá", "Ớt", "Cà chua", "Hoa cảnh"]'::jsonb,
  NULL,
  62,
  TRUE,
  NULL,
  NULL,
  'UF/IFAS Extension',
  'https://gardeningsolutions.ifas.ufl.edu/care/pests-and-diseases/pests/integrated-pest-management/',
  'Nguồn IPM khuyến nghị phòng ngừa chủ động, vệ sinh khu trồng và giảm áp lực sâu bệnh.'
),
(
  'han-che-de-co-dai-canh-goc-cay',
  'Hạn chế để cỏ dại cạnh gốc cây',
  'Cỏ dại gần gốc có thể là nơi trú ẩn của sâu hại.',
  'Cỏ dại làm khu trồng rậm và giữ ẩm cục bộ, tạo điều kiện cho sâu bệnh ẩn náu. Dọn cỏ định kỳ giúp thông thoáng và dễ quan sát cây hơn. Khi làm cỏ, tránh làm tổn thương rễ nông của cây trồng chính.',
  'Kiểm soát sâu hại',
  '["Rau màu", "Cây ăn quả", "Hoa cảnh", "Ngũ cốc"]'::jsonb,
  NULL,
  61,
  TRUE,
  NULL,
  NULL,
  'UF/IFAS Extension',
  'https://gardeningsolutions.ifas.ufl.edu/care/pests-and-diseases/pests/integrated-pest-management/',
  'Nguồn IPM khuyến nghị phòng ngừa chủ động, vệ sinh khu trồng và giảm áp lực sâu bệnh.'
),
(
  'quan-sat-vet-chich-hoac-la-xoan-bat-thuong',
  'Quan sát vết chích hoặc lá xoăn bất thường',
  'Lá xoăn và vết chích có thể là dấu hiệu côn trùng chích hút.',
  'Khi lá xoăn bất thường hoặc có nhiều chấm nhỏ, nên kiểm tra sâu hơn ở mặt dưới lá. Đây có thể là dấu hiệu sớm của nhóm côn trùng chích hút. Phát hiện kịp thời giúp hạn chế ảnh hưởng lên đợt lá non mới.',
  'Kiểm soát sâu hại',
  '["Ớt", "Cà chua", "Rau thơm", "Hoa cảnh"]'::jsonb,
  NULL,
  60,
  TRUE,
  NULL,
  NULL,
  'Clemson Cooperative Extension',
  'https://hgic.clemson.edu/factsheet/integrated-pest-management-i-p-m-for-aphids/',
  'Nguồn IPM khuyến nghị kiểm tra mặt dưới lá và chồi non để phát hiện rệp sớm.'
),
(
  'kiem-tra-bay-dinh-neu-co-su-dung',
  'Kiểm tra bẫy dính nếu có dùng',
  'Theo dõi bẫy dính giúp ước lượng sớm xu hướng côn trùng trong vườn.',
  'Nếu đang dùng bẫy dính, nên kiểm tra định kỳ để nhận biết mật độ côn trùng thay đổi. Thông tin này hữu ích cho việc quyết định tăng theo dõi khu vực nào. Kết hợp dữ liệu bẫy với quan sát lá sẽ chính xác hơn.',
  'Kiểm soát sâu hại',
  '["Rau chậu", "Hoa cảnh", "Ớt", "Cà chua"]'::jsonb,
  NULL,
  59,
  TRUE,
  NULL,
  NULL,
  'University of California Agriculture and Natural Resources',
  'https://ipm.ucanr.edu/',
  'Nguồn IPM khuyến nghị giám sát thường xuyên, xử lý sớm và ưu tiên biện pháp canh tác an toàn.'
),
(
  'quan-sat-cay-ngay-sau-mua',
  'Quan sát cây sau mưa',
  'Sau mưa nên kiểm tra nhanh để phát hiện vùng lá tổn thương.',
  'Mưa lớn có thể làm dập lá, bắn đất và tạo điều kiện cho bệnh lá xuất hiện. Quan sát sớm giúp bạn xử lý kịp thời những phần bị ảnh hưởng. Đây là bước quan trọng trong mùa mưa kéo dài.',
  'Chăm sóc sau mưa',
  '["Cà chua", "Dưa leo", "Ớt", "Rau cải"]'::jsonb,
  NULL,
  58,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/disease-management/late-blight',
  'Nguồn khuyến nghị tăng giám sát khi thời tiết ẩm mát và giảm nguy cơ lây bệnh trong vườn.'
),
(
  'loai-bo-nuoc-dong-o-khay-hoac-chau',
  'Loại bỏ nước đọng ở khay hoặc chậu',
  'Nước đọng lâu làm tăng rủi ro úng rễ và bệnh do ẩm.',
  'Sau mưa, cần kiểm tra khay và đáy chậu để tránh nước ứ kéo dài. Rễ bị ngâm nước lâu thường suy yếu và giảm sức chống chịu. Điều chỉnh thoát nước sớm sẽ giúp cây phục hồi tốt hơn.',
  'Chăm sóc sau mưa',
  '["Hoa cảnh", "Rau chậu", "Ớt", "Cà chua"]'::jsonb,
  NULL,
  57,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'rua-nhe-dat-ban-len-la-khi-can',
  'Rửa nhẹ đất bắn lên lá nếu cần',
  'Làm sạch đất bắn trên lá giúp giảm nguy cơ lây mầm bệnh từ đất.',
  'Sau mưa lớn, đất có thể bám lên lá thấp và mang theo mầm bệnh. Có thể rửa nhẹ vào thời điểm lá còn thời gian khô trong ngày. Tránh chà mạnh gây tổn thương bề mặt lá.',
  'Chăm sóc sau mưa',
  '["Cà chua", "Dưa leo", "Dâu tây", "Ớt"]'::jsonb,
  NULL,
  56,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'kiem-tra-dau-hieu-nam-sau-mua-keo-dai',
  'Kiểm tra dấu hiệu nấm sau mưa kéo dài',
  'Mưa kéo dài làm nguy cơ nấm lá tăng mạnh, cần giám sát kỹ.',
  'Quan sát các mảng mốc, đốm nâu hoặc lớp phấn bất thường sau chuỗi ngày mưa. Triệu chứng ban đầu thường nhỏ nhưng có thể lan nhanh nếu không theo dõi. Khi mức độ tăng nhanh, nên tham khảo chuyên gia nông nghiệp.',
  'Chăm sóc sau mưa',
  '["Cà chua", "Bầu bí", "Rau lá", "Ớt"]'::jsonb,
  NULL,
  55,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/disease-management/late-blight',
  'Nguồn khuyến nghị tăng giám sát khi thời tiết ẩm mát và giảm nguy cơ lây bệnh trong vườn.'
),
(
  'lam-thong-thoang-khu-vuc-trong-sau-mua',
  'Làm thông thoáng khu vực trồng sau mưa',
  'Tăng thông thoáng sau mưa giúp lá khô nhanh và giảm bệnh.',
  'Sau mưa, nên dọn bớt vật cản và tỉa nhẹ tán lá rậm để không khí lưu thông tốt. Việc giảm ẩm tồn đọng sẽ hạn chế điều kiện phát sinh bệnh. Đây là bước chăm sóc đơn giản nhưng hiệu quả cao.',
  'Chăm sóc sau mưa',
  '["Rau cải", "Cà chua", "Ớt", "Hoa cảnh"]'::jsonb,
  NULL,
  54,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'don-bo-qua-va-la-bi-thoi',
  'Dọn bỏ quả hoặc lá bị thối',
  'Tàn dư thối hỏng nên loại bỏ sớm để giảm nguồn lây.',
  'Quả và lá thối có thể chứa nhiều mầm bệnh gây lây lan trong khu trồng. Thu gom và xử lý đúng cách giúp giảm nguy cơ tái nhiễm. Vệ sinh đều đặn sẽ giúp vườn ổn định hơn theo thời gian.',
  'Vệ sinh vườn',
  '["Cà chua", "Dâu tây", "Ớt", "Cây ăn quả"]'::jsonb,
  NULL,
  53,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'giu-dat-thoat-nuoc-tot',
  'Giữ đất thoát nước tốt',
  'Đất thoát nước tốt giúp rễ khỏe và giảm bệnh vùng rễ.',
  'Đất bí nước làm rễ thiếu oxy và dễ suy yếu trong thời gian ngắn. Cải thiện cấu trúc đất giúp thoát nước tốt hơn sau mưa hoặc tưới. Khi rễ khỏe, cây thường chống chịu bệnh tốt hơn.',
  'Quản lý đất',
  '["Ớt", "Cà chua", "Dưa leo", "Dâu tây"]'::jsonb,
  NULL,
  52,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'phu-goc-han-che-dat-ban-len-la',
  'Phủ gốc để hạn chế đất bắn lên lá',
  'Lớp phủ gốc giúp giảm bắn đất mang mầm bệnh lên tán lá.',
  'Khi mưa tưới mạnh, đất dễ bắn lên lá thấp và tăng nguy cơ nhiễm bệnh. Phủ gốc phù hợp giúp hạn chế hiện tượng này và giữ ẩm đất ổn định hơn. Đây là biện pháp hữu ích trong mùa mưa.',
  'Quản lý đất',
  '["Cà chua", "Dưa leo", "Dâu tây", "Ớt"]'::jsonb,
  NULL,
  51,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'luan-canh-cay-trong-khi-co-the',
  'Luân canh cây trồng khi có thể',
  'Luân canh giúp giảm tích lũy mầm bệnh theo vụ.',
  'Trồng lặp lại cùng họ cây ở một vị trí nhiều vụ liền có thể làm bệnh tích tụ. Luân canh hợp lý giúp cắt vòng đời một số tác nhân gây hại. Đây là chiến lược bền vững cho quản lý sức khỏe đất và cây.',
  'Quản lý đất',
  '["Cà chua", "Khoai tây", "Đậu", "Rau cải"]'::jsonb,
  NULL,
  50,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'khong-de-dat-ung-nuoc-lau',
  'Không để đất úng nước lâu',
  'Úng kéo dài làm cây suy và tăng nguy cơ bệnh rễ.',
  'Nếu đất đọng nước nhiều giờ, nên cải thiện thoát nước càng sớm càng tốt. Úng lâu ngày khiến cây giảm sinh trưởng và dễ nhiễm bệnh. Theo dõi khu vực trũng để điều chỉnh luống hoặc chậu phù hợp.',
  'Quản lý đất',
  '["Rau ăn lá", "Ớt", "Cà chua", "Đậu"]'::jsonb,
  NULL,
  49,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/disease-management/late-blight',
  'Nguồn khuyến nghị tăng giám sát khi thời tiết ẩm mát và giảm nguy cơ lây bệnh trong vườn.'
),
(
  'bo-sung-chat-huu-co-da-hoai-muc',
  'Bổ sung chất hữu cơ đã xử lý hoai mục',
  'Hữu cơ hoai mục giúp cải thiện đất và hỗ trợ hệ rễ khỏe.',
  'Vật liệu hữu cơ đã hoai mục giúp đất tơi xốp và giữ ẩm cân bằng hơn. Đất khỏe sẽ tạo điều kiện cho rễ phát triển ổn định và giảm stress cho cây. Nên dùng nguồn hữu cơ đã xử lý kỹ để đảm bảo an toàn.',
  'Quản lý đất',
  '["Rau màu", "Cây ăn quả", "Hoa cảnh", "Ngũ cốc"]'::jsonb,
  NULL,
  48,
  TRUE,
  NULL,
  NULL,
  'University of California Agriculture and Natural Resources',
  'https://ipm.ucanr.edu/',
  'Nguồn IPM khuyến nghị giám sát thường xuyên, xử lý sớm và ưu tiên biện pháp canh tác an toàn.'
),
(
  'khong-de-tan-du-cay-benh-trong-vuon',
  'Không để tàn dư cây bệnh trong vườn',
  'Tàn dư cây bệnh tồn lưu lâu sẽ làm tăng nguy cơ tái phát.',
  'Sau khi dọn cây bệnh, không nên để lại phần tàn dư ngay trong khu trồng. Vệ sinh tốt giúp cắt giảm nguồn mầm bệnh trước vụ mới. Kết hợp với theo dõi định kỳ để quản lý bệnh hiệu quả hơn.',
  'Vệ sinh vườn',
  '["Cà chua", "Ớt", "Rau cải", "Cây ăn quả"]'::jsonb,
  NULL,
  47,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'bo-tri-hang-cay-theo-huong-don-gio',
  'Bố trí hàng cây theo hướng đón gió',
  'Hướng trồng hợp lý giúp tăng lưu thông không khí tự nhiên.',
  'Khi bố trí hàng cây theo hướng gió địa phương, tán lá sẽ khô nhanh hơn sau mưa tưới. Điều này giúp giảm độ ẩm tồn đọng trong luống trồng. Cách bố trí hợp lý cũng hỗ trợ kiểm tra sâu bệnh thuận tiện hơn.',
  'Môi trường trồng',
  '["Cà chua", "Ớt", "Rau cải", "Ngũ cốc"]'::jsonb,
  NULL,
  46,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'giam-tuoi-khi-mua-lien-tuc',
  'Giảm tưới khi mưa liên tục',
  'Mưa liên tục cần giảm tưới để tránh dư ẩm vùng rễ.',
  'Khi lượng mưa đã đủ, việc tưới thêm thường không cần thiết và dễ gây úng. Nên kiểm tra độ ẩm đất trước mỗi lần tưới trong mùa mưa. Điều chỉnh kịp thời sẽ giúp cây ổn định hơn.',
  'Chăm sóc theo mùa',
  '["Rau ăn lá", "Cà chua", "Ớt", "Dưa leo"]'::jsonb,
  NULL,
  45,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/disease-management/late-blight',
  'Nguồn khuyến nghị tăng giám sát khi thời tiết ẩm mát và giảm nguy cơ lây bệnh trong vườn.'
),
(
  'theo-doi-cay-trong-dot-lanh-am',
  'Theo dõi cây trong đợt lạnh ẩm',
  'Đợt lạnh ẩm có thể làm một số bệnh lá tiến triển nhanh hơn.',
  'Nhiệt độ giảm kèm độ ẩm cao là thời điểm cần tăng tần suất theo dõi cây. Hãy chú ý các đốm mới, mốc bất thường và lá héo cục bộ. Ghi lại diễn biến mỗi ngày để quyết định chăm sóc phù hợp.',
  'Chăm sóc theo mùa',
  '["Cà chua", "Khoai tây", "Ớt", "Rau lá"]'::jsonb,
  NULL,
  44,
  TRUE,
  NULL,
  NULL,
  'Penn State Extension',
  'https://extension.psu.edu/tomato-potato-late-blight-in-the-home-garden/',
  'Nguồn nhấn mạnh phát hiện sớm, loại bỏ mô bệnh và theo dõi sát cây có nguy cơ cao.'
),
(
  'tan-dung-anh-sang-sang-som-cho-cay',
  'Tận dụng ánh sáng sáng sớm cho cây',
  'Ánh sáng buổi sáng hỗ trợ cây phục hồi sau đêm ẩm.',
  'Đặt cây nhận nắng sáng giúp lá khô nhanh và giảm nguy cơ ẩm kéo dài. Ánh sáng dịu buổi sáng cũng hỗ trợ quang hợp ổn định cho nhiều loại cây. Nên tránh để tán cây che kín lẫn nhau trong khung giờ này.',
  'Ánh sáng',
  '["Rau thơm", "Rau lá", "Cà chua", "Ớt"]'::jsonb,
  NULL,
  43,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'kiem-soat-bong-ram-qua-day-tren-tan-cay',
  'Kiểm soát bóng râm quá dày trên tán cây',
  'Bóng râm dày có thể làm lá ẩm lâu và giảm thông khí.',
  'Nếu tán che quá kín, nên tỉa nhẹ hoặc điều chỉnh vị trí để tăng ánh sáng khuếch tán. Mục tiêu là giúp lá khô nhanh và giảm áp lực bệnh. Theo dõi phản ứng của cây sau điều chỉnh để tối ưu dần.',
  'Ánh sáng',
  '["Hoa cảnh", "Rau chậu", "Ớt", "Cà tím"]'::jsonb,
  NULL,
  42,
  TRUE,
  NULL,
  NULL,
  'University of California Agriculture and Natural Resources',
  'https://ipm.ucanr.edu/',
  'Nguồn IPM khuyến nghị giám sát thường xuyên, xử lý sớm và ưu tiên biện pháp canh tác an toàn.'
),
(
  'chuan-bi-che-mua-cho-cay-trong-chau',
  'Chuẩn bị che mưa cho cây trồng chậu',
  'Che mưa chủ động giúp giảm dập lá và hạn chế úng chậu.',
  'Trong đợt mưa lớn liên tục, có thể di chuyển chậu vào nơi thoáng có mái che phù hợp. Biện pháp này giúp tránh mưa dội trực tiếp làm đất bắn lên lá và giảm úng. Sau mưa vẫn cần đảm bảo cây có ánh sáng cần thiết.',
  'Chăm sóc theo mùa',
  '["Hoa cảnh", "Rau chậu", "Ớt", "Cà chua"]'::jsonb,
  NULL,
  41,
  TRUE,
  NULL,
  NULL,
  'UF/IFAS Extension',
  'https://gardeningsolutions.ifas.ufl.edu/care/pests-and-diseases/pests/integrated-pest-management/',
  'Nguồn IPM khuyến nghị phòng ngừa chủ động, vệ sinh khu trồng và giảm áp lực sâu bệnh.'
),
(
  'lap-ke-hoach-kiem-tra-vuon-theo-tuan',
  'Lập kế hoạch kiểm tra vườn theo tuần',
  'Lịch kiểm tra cố định giúp không bỏ sót dấu hiệu bất thường.',
  'Nên có lịch kiểm tra vườn theo tuần với các điểm cố định như lá non, mặt dưới lá và vùng gốc. Theo dõi đều giúp phát hiện sớm vấn đề và xử lý nhẹ nhàng hơn. Dữ liệu lịch sử cũng hữu ích cho đánh giá dài hạn.',
  'Theo dõi cây',
  '["Rau cải", "Ớt", "Cà chua", "Cây ăn quả"]'::jsonb,
  NULL,
  40,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'giu-loi-di-vuon-kho-rao-de-han-che-lay-benh',
  'Giữ lối đi vườn khô ráo để hạn chế lây bệnh',
  'Lối đi bùn ướt dễ mang mầm bệnh bám sang khu vực khác.',
  'Khi lối đi quá ướt, bùn đất có thể bám giày và lan sang các luống cây. Giữ khu vực đi lại sạch, thoát nước tốt sẽ giảm nguy cơ lây nhiễm cơ học. Đây là chi tiết nhỏ nhưng có giá trị phòng bệnh cao.',
  'Vệ sinh vườn',
  '["Rau màu", "Cây ăn quả", "Hoa cảnh", "Ngũ cốc"]'::jsonb,
  NULL,
  39,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'quan-sat-vet-thuong-co-hoc-tren-la-va-than',
  'Quan sát vết thương cơ học trên lá và thân',
  'Vết thương hở có thể là cửa ngõ cho bệnh xâm nhập.',
  'Sau gió mạnh hoặc thao tác làm vườn, nên kiểm tra các vết trầy xước trên cây. Vết thương có thể tạo điều kiện cho tác nhân bệnh xâm nhập nhanh hơn. Theo dõi vùng tổn thương trong vài ngày để xử lý kịp thời.',
  'Theo dõi cây',
  '["Cà chua", "Ớt", "Hoa cảnh", "Cây ăn quả"]'::jsonb,
  NULL,
  38,
  TRUE,
  NULL,
  NULL,
  'University of California Agriculture and Natural Resources',
  'https://ipm.ucanr.edu/',
  'Nguồn IPM khuyến nghị giám sát thường xuyên, xử lý sớm và ưu tiên biện pháp canh tác an toàn.'
),
(
  'dieu-chinh-tuoi-theo-giai-doan-ra-hoa',
  'Điều chỉnh tưới theo giai đoạn ra hoa',
  'Giai đoạn ra hoa cần quản lý ẩm ổn định, tránh dao động lớn.',
  'Khi cây ra hoa, độ ẩm đất nên được giữ đều để hạn chế stress sinh lý. Tưới quá thất thường có thể làm cây yếu và giảm sức chống chịu. Kết hợp theo dõi thời tiết để điều chỉnh lượng tưới hợp lý.',
  'Tưới nước',
  '["Cà chua", "Ớt", "Dưa leo", "Đậu"]'::jsonb,
  NULL,
  37,
  TRUE,
  NULL,
  NULL,
  'UF/IFAS Extension',
  'https://gardeningsolutions.ifas.ufl.edu/care/pests-and-diseases/pests/integrated-pest-management/',
  'Nguồn IPM khuyến nghị phòng ngừa chủ động, vệ sinh khu trồng và giảm áp lực sâu bệnh.'
),
(
  'tang-giam-mat-do-che-phu-goc-theo-mua',
  'Tăng giảm lớp phủ gốc theo mùa',
  'Điều chỉnh lớp phủ giúp cân bằng ẩm đất theo thời tiết.',
  'Mùa nắng có thể tăng lớp phủ để giữ ẩm, mùa mưa cần kiểm tra để tránh bí gốc. Quản lý lớp phủ linh hoạt giúp đất ổn định và giảm bắn đất lên lá. Đây là biện pháp dễ áp dụng cho cả chậu và luống.',
  'Chăm sóc theo mùa',
  '["Rau cải", "Cà chua", "Ớt", "Dâu tây"]'::jsonb,
  NULL,
  36,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'theo-doi-do-thong-thoang-tan-cay-moi-thang',
  'Theo dõi độ thông thoáng tán cây mỗi tháng',
  'Đánh giá định kỳ giúp duy trì tán cây cân bằng và ít bệnh.',
  'Mỗi tháng nên kiểm tra lại mật độ tán để kịp tỉa khi cây phát triển nhanh. Tán quá dày thường giữ ẩm và tăng nguy cơ bệnh lá. Duy trì thông thoáng sẽ giúp các biện pháp chăm sóc khác hiệu quả hơn.',
  'Môi trường trồng',
  '["Cà chua", "Ớt", "Hoa hồng", "Cây ăn quả"]'::jsonb,
  NULL,
  35,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'uu-tien-phat-hien-som-thay-vi-xu-ly-muon',
  'Ưu tiên phát hiện sớm thay vì xử lý muộn',
  'Phát hiện sớm thường giúp giảm mức độ thiệt hại rõ rệt.',
  'Quan sát thường xuyên giúp nhận biết vấn đề khi mới xuất hiện, lúc này xử lý thường nhẹ và hiệu quả hơn. Chờ đến khi triệu chứng nặng mới can thiệp sẽ tốn thời gian phục hồi hơn. Hãy duy trì thói quen theo dõi ngắn mỗi ngày.',
  'Theo dõi cây',
  '["Rau lá", "Cà chua", "Ớt", "Hoa cảnh"]'::jsonb,
  NULL,
  34,
  TRUE,
  NULL,
  NULL,
  'University of California Agriculture and Natural Resources',
  'https://ipm.ucanr.edu/',
  'Nguồn IPM khuyến nghị giám sát thường xuyên, xử lý sớm và ưu tiên biện pháp canh tác an toàn.'
),
(
  'giu-can-bang-am-do-va-anh-sang-trong-nha-luoi',
  'Giữ cân bằng ẩm độ và ánh sáng trong nhà lưới',
  'Nhà lưới cần quản lý đồng thời ẩm độ và ánh sáng để giảm bệnh.',
  'Môi trường nhà lưới dễ tích nhiệt và ẩm nếu thiếu thông gió phù hợp. Điều chỉnh thông khí và ánh sáng giúp cây khỏe, giảm áp lực bệnh lá. Theo dõi cảm quan hằng ngày để tối ưu điều kiện trồng.',
  'Môi trường trồng',
  '["Rau lá", "Rau thơm", "Ớt", "Cà chua"]'::jsonb,
  NULL,
  33,
  TRUE,
  NULL,
  NULL,
  'UF/IFAS Extension',
  'https://gardeningsolutions.ifas.ufl.edu/care/pests-and-diseases/pests/integrated-pest-management/',
  'Nguồn IPM khuyến nghị phòng ngừa chủ động, vệ sinh khu trồng và giảm áp lực sâu bệnh.'
),
(
  'kiem-tra-vung-goc-sau-moi-lan-tuoi',
  'Kiểm tra vùng gốc sau mỗi lần tưới',
  'Quan sát vùng gốc giúp phát hiện sớm úng hoặc đóng váng đất.',
  'Sau khi tưới, nên kiểm tra xem nước có thoát đều quanh gốc hay không. Nếu đất đóng váng hoặc đọng nước, cần điều chỉnh để tránh hại rễ. Vùng gốc khỏe là nền tảng cho cả cây phát triển ổn định.',
  'Quản lý đất',
  '["Cà chua", "Ớt", "Rau cải", "Dưa leo"]'::jsonb,
  NULL,
  32,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/planting-and-growing-guides/managing-plant-diseases-home-garden',
  'Nguồn nhấn mạnh quản lý độ ẩm, vệ sinh vườn và phát hiện sớm để phòng bệnh cây.'
),
(
  'quan-ly-co-dai-theo-chu-ky-ngan',
  'Quản lý cỏ dại theo chu kỳ ngắn',
  'Dọn cỏ thường xuyên giúp khu trồng sạch và dễ quan sát sâu bệnh.',
  'Không nên để cỏ dại phát triển quá rậm rồi mới xử lý một lần. Dọn theo chu kỳ ngắn giúp giảm nơi trú ẩn của sâu hại và hạn chế cạnh tranh dinh dưỡng. Khu vườn sạch cũng hỗ trợ phát hiện triệu chứng bệnh sớm.',
  'Vệ sinh vườn',
  '["Rau màu", "Ngũ cốc", "Cây ăn quả", "Hoa cảnh"]'::jsonb,
  NULL,
  31,
  TRUE,
  NULL,
  NULL,
  'NC State Extension',
  'https://content.ces.ncsu.edu/extension-gardener-handbook/8-integrated-pest-management-ipm',
  'Nguồn IPM khuyến nghị theo dõi định kỳ, thông thoáng tán lá và quản lý môi trường trồng.'
),
(
  'quan-sat-la-sau-khi-tia-de-danh-gia-phan-ung-cay',
  'Quan sát lá sau khi tỉa để đánh giá phản ứng cây',
  'Theo dõi sau tỉa giúp điều chỉnh cường độ cắt tỉa hợp lý hơn.',
  'Sau mỗi đợt tỉa, nên quan sát cây trong vài ngày để xem mức hồi phục. Nếu cây yếu đi nhanh, cần giảm cường độ tỉa ở lần kế tiếp. Theo dõi phản ứng thực tế sẽ giúp bạn xây dựng quy trình chăm sóc phù hợp từng giống.',
  'Cắt tỉa',
  '["Cà chua", "Ớt", "Hoa cảnh", "Cây ăn quả"]'::jsonb,
  NULL,
  30,
  TRUE,
  NULL,
  NULL,
  'University of Minnesota Extension',
  'https://extension.umn.edu/plant-diseases/leaf-spot-diseases-trees-and-shrubs',
  'Nguồn khuyến nghị cắt tỉa hợp lý, vệ sinh tàn dư và giảm điều kiện lây lan bệnh lá.'
),
(
  'duy-tri-thoi-quen-kiem-tra-vuon-vao-sang-som',
  'Duy trì thói quen kiểm tra vườn vào sáng sớm',
  'Kiểm tra sáng sớm giúp phát hiện bất thường trước khi nhiệt độ tăng cao.',
  'Buổi sáng là thời điểm dễ quan sát độ tươi của lá, vết bệnh mới và dấu hiệu côn trùng. Phát hiện sớm trong ngày giúp bạn chủ động xử lý và theo dõi tiếp diễn biến. Đây là thói quen nhỏ tạo khác biệt lớn cho quản lý vườn.',
  'Theo dõi cây',
  '["Rau lá", "Cà chua", "Ớt", "Hoa cảnh"]'::jsonb,
  NULL,
  29,
  TRUE,
  NULL,
  NULL,
  'University of California Agriculture and Natural Resources',
  'https://ipm.ucanr.edu/',
  'Nguồn IPM khuyến nghị giám sát thường xuyên, xử lý sớm và ưu tiên biện pháp canh tác an toàn.'
),
(
  'kiem-tra-mat-duoi-la-sau-dot-nong-am',
  'Kiểm tra mặt dưới lá sau đợt nóng ẩm',
  'Nóng ẩm xen kẽ là thời điểm sâu bệnh dễ bùng lên nhanh.',
  'Sau các đợt nóng ẩm, rệp và nấm bệnh có thể tăng nhanh trên lá non. Hãy kiểm tra kỹ mặt dưới lá và các điểm giao giữa lá với thân. Nếu xuất hiện dấu hiệu bất thường liên tục, nên tăng mức theo dõi trong tuần.',
  'Chăm sóc theo mùa',
  '["Ớt", "Cà chua", "Dưa leo", "Rau cải"]'::jsonb,
  NULL,
  28,
  TRUE,
  NULL,
  NULL,
  'Clemson Cooperative Extension',
  'https://hgic.clemson.edu/factsheet/integrated-pest-management-i-p-m-for-aphids/',
  'Nguồn IPM khuyến nghị kiểm tra mặt dưới lá và chồi non để phát hiện rệp sớm.'
)
ON CONFLICT (slug)
DO UPDATE SET
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  content = EXCLUDED.content,
  category = EXCLUDED.category,
  suitable_plants = EXCLUDED.suitable_plants,
  related_disease_id = EXCLUDED.related_disease_id,
  priority = EXCLUDED.priority,
  is_active = EXCLUDED.is_active,
  start_date = EXCLUDED.start_date,
  end_date = EXCLUDED.end_date,
  source_name = EXCLUDED.source_name,
  source_url = EXCLUDED.source_url,
  source_note = EXCLUDED.source_note,
  updated_at = NOW();

-- Kiểm tra sau khi seed
-- SELECT COUNT(*) FROM care_tips;

-- SELECT slug, title, category, priority, is_active, source_name
-- FROM care_tips
-- ORDER BY priority DESC
-- LIMIT 20;

-- SELECT category, COUNT(*)
-- FROM care_tips
-- GROUP BY category
-- ORDER BY COUNT(*) DESC;

-- SELECT slug, title, source_name, source_url
-- FROM care_tips
-- WHERE source_url IS NULL OR source_name IS NULL;